language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("PathfinderRouting"); Pkg.test("PathfinderRouting")'
after_success:
  - julia -e 'cd(Pkg.dir("PathfinderRouting")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
